### ISSUE TITLE
discriminação entre barras

### ISSUE THREAD

**Issue by mariaraujo815** [pylearners/Projeto2#3]
Se o som1 foi emitido e o animal tocou na barra esquerda, liberar 0,5ml de recompensa
Caso contrário não liberar nada;

Se o som 2 foi emitido e o animal tocou na barra direita, liberar 0,5ml de recompensa
Caso contrário não liberar nada;

Se o experimento foi realizado 50x em 30min, apresentar que o experimento seguirá para a próxima fase.

**Comment by FabioISD** [comment]
Feito!
